### PR TITLE
Update terraref-application.yml

### PR DESCRIPTION
**Pull request by dlebauer**
@gsrohde could you please deploy on bety6? I've edited the version on bety6.ncsa.illinois.edu in /home/bety/bety/config and done `touch ../tmp/restart.txt` but the changes don't appear on terraref.ncsa.illinois.edu. Could you please make sure that these changes show up there?

### CODE REVIEW

**Comment by gsrohde** [comment]
@dlebauer I deployed the version from PR #554.  See if it's OK.  If so, close this.

**Comment by dlebauer** [comment]
It looks ok except the broken or invisible link to the traitvis app

**Comment by gsrohde** [comment]
I've replaced the changes for this pull request with a simple fix to the link to the traitvis app.

**Comment by gsrohde** [comment]
@dlebauer I went ahead and merge (a modified version of) this and closed.  You can double-check to see what's deployed on the terra-ref BETYdb site looks OK.

**Pull request merged**
