### PR TITLE
Updated some Gems per GitHub recommendations.

### PR DESCRIPTION
**Pull request by gsrohde**

### CODE REVIEW

**Comment by dlebauer** [comment]
Is this still relevant? Should we go ahead and merge? Or has this been superseded by subsequent updates and should be closed?

**Comment by gsrohde** [comment]
@dlebauer I think it's been partly superseded and it'd be better to start fresh if we want to do a general Gem upgrade.

Also, I think @robkooper set up [automated security fixes](https://help.github.com/en/articles/configuring-automated-security-fixes), though if this is so, I'm not sure [there has been only one automatic PR generated since May 23](https://github.com/PecanProject/bety/pulls?utf8=%E2%9C%93&q=is%3Apr+dependabot) when there are currently [three security alerts](https://github.com/PecanProject/bety/network/alerts) listed for BETYdb.

**Comment by robkooper** [comment]
Yes github now checks gemfile and creates some pull requests, here is a list: https://github.com/PecanProject/bety/pulls?q=is%3Apr+author%3Aapp%2Fdependabot

**Comment by gsrohde** [comment]
@robkooper What I'm not clear about is why, of the [three security alerts](https://github.com/PecanProject/bety/network/alerts) listed, only the first one seems to have generated a pull request.  Are PRs generated only for high severity vulnerabilities?  Also, it's not clear to me, if the PR addressing the nokogiri vulnerability has been merged, why it is still listed on the alerts page.

So it seems to me that if we want to take these security issues seriously, some manual monitoring may be needed.

**Comment by robkooper** [comment]
I think they are conservative in that they only create a pull request if and only if that should not break anything.

**Pull request closed without merging**
