### PR TITLE
Rails51 with asset pipeline and jquery in gems

### PR DESCRIPTION
**Pull request by gsrohde**
@robkooper Could you deploy this for testing?

You'll need to compile the assets with

```
rake assets:precompile RAILS_ENV=production
```

or, if you are deploying to a sub-URI, as is probably the case, with

```
rake assets:precompile RAILS_ENV=production RAILS_RELATIVE_URL_ROOT="/bety"
```

(assuming the subdirectory deployed to is called "bety").

### CODE REVIEW

**Comment by robkooper** [comment]
Probably need to add rake assets:precompile RAILS_ENV=production RAILS_RELATIVE_URL_ROOT="/bety" to the entrypoint code.

**Comment by robkooper** [comment]
Need to make sure we have ruby 2.2 or later:
```
apt-get install ruby2.2
update-alternatives --config ruby
```

**Comment by robkooper** [comment]
@gsrohde got the following error:

```
bundle exec rake assets:precompile RAILS_ENV=production RAILS_RELATIVE_URL_ROOT="/bety"
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'coffee-rails'.
Gem Load Error is: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
```

**Comment by gsrohde** [comment]
@robkooper We don't actually use CoffeeScript at this point, and even though I might eventually want to be able to use it, for now you could try commenting out the coffee-rails Gem and see if that suffices to get compilation to work.

**Comment by gsrohde** [comment]
@robkooper @max-zilla @dlebauer @craig-willis All: This version—Rails 5.1 with the asset pipeline enabled—is ready for testing at http://pecan-dev.ncsa.illinois.edu/bety.

**Comment by robkooper** [comment]
Some of the changes needed for docker to be able to use this are in PR #572

**Comment by max-zilla** [comment]
I tested the endpoints we use for terraref pipeline:
- sites
- traits
- experiments
- cultivars

...logged in as carya. everything looks good.

**Comment by gsrohde** [comment]
@all The test deployment is once again ready for testing at http://pecan-dev.ncsa.illinois.edu/bety.

**Comment by dlebauer** [comment]
What happened to the schema documentation at http://pecan-dev.ncsa.illinois.edu/bety/schemas?

**Comment by gsrohde** [comment]
@dlebauer The apipie problem was fixed by reverting to the previous version and by adding some config settings in its initialization file.

@robkooper R needs package ggplot2 in order to generate the priors preview images.  Could you install it?

The SchemaSpy documentation generator needs some set-up and then it needs to be run.  I need to add a section about this in the installation documentation.  The SchemaSpy docs are there now, but the images are not.  @robkooper SchemaSpy needs dot version 2.2.1 or a version greater than 2.4 (from www.graphviz.org) in order to generate diagram images.  Could you install this?

**Pull request merged**
