### PR TITLE
auto update documentation

### PR DESCRIPTION
**Pull request by phenolphtalein**
Created a rake task that updates the schema documentation using schemaSpy. This task will automatically be executed with <code>rake db:migrate</code>.
Before using the code, you'll need to modify <code>update.sh</code> to contain the correct paths to the files needed by schemaSpy (see the comments in <code>update.sh</code>.)
The executable for schemaSpy can be found here:https://www.dropbox.com/s/nayr6nfzlh7sc5l/schemaSpy.jar?dl=0

### CODE REVIEW

**Comment by dlebauer** [comment]
Please 
* fork this repository PecanProject/SchemaSpy-ng
* add modified source code
* remove SchemaSpy code from betydb
* create release and attach binary

**Comment by phenolphtalein** [comment]
Forked the repository into PecanProject.
See https://github.com/PecanProject/SchemaSpy-ng/pull/1

**Comment by gsrohde** [comment]
@phenolphtalein The schemaSpy.jar jar file at https://www.dropbox.com/s/nayr6nfzlh7sc5l/schemaSpy.jar?dl=0 no longer exists.  I tried the copy in the release at https://github.com/PecanProject/SchemaSpy-ng/releases but I get an error message when I do `java -jar schemaSpy.jar` ("Invalid or corrupt jarfile schemaSpy.jar").  I tried compiling from source using the instructions at https://github.com/PecanProject/SchemaSpy-ng, but those instructions are not clear.  For example, it says to "cd into the directory containing the source files", but there are multiple directories containing *.java files.  I tried using the top-level one `/src/main/java/net/sourceforge/schemaspy` but couldn't successfully compile using the instructions.  Please help.

**Comment by phenolphtalein** [comment]
I might have moved the files on my computer. I'll update the documentation when I find it.

**Comment by gsrohde** [comment]
@phenolphtalein Any progress on this?

**Comment by phenolphtalein** [comment]
Sorry about the delay...
The executable is at https://www.dropbox.com/s/j50hk7cbqw7680u/schemaSpy.jar?dl=0
To compile from source:
<code>cd /path/to/scr/</code>
<code>find . -name *.java > sources</code>
<code>javac @sources</code>
<code>find . -name *.class> classes</code>
<code>jar cf schemaSpy.jar @classes</code>

**Comment by dlebauer** [comment]
What is 'path/to/scr/' in this repository?

**Comment by gsrohde** [comment]
@phenolphtalein When I try to use the precompiled JAR file, I get this error:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: schemaspy/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

If I try to follow your instructions for compiling from source, I get these errors:

`javac @sources`

```
./src/test/java/net/sourceforge/schemaspy/util/VersionTest.java:29: cannot find symbol
symbol  : class Version
location: class net.sourceforge.schemaspy.util.VersionTest
    private final Version twoNineOne = new Version("2.9.1");
                  ^
./src/test/java/net/sourceforge/schemaspy/util/VersionTest.java:30: cannot find symbol
symbol  : class Version
location: class net.sourceforge.schemaspy.util.VersionTest
    private final Version twoTen = new Version("2.10");
                  ^
./src/test/java/net/sourceforge/schemaspy/util/VersionTest.java:31: cannot find symbol
symbol  : class Version
location: class net.sourceforge.schemaspy.util.VersionTest
    private final Version twoTenOne = new Version("2.10.1");
                  ^
./src/test/java/net/sourceforge/schemaspy/util/RailsNamingTest.java:38: cannot find symbol
symbol  : variable Inflection
location: class net.sourceforge.schemaspy.util.RailsNamingTest
        String primaryTableName = Inflection.pluralize(singular);
                                  ^
./src/test/java/net/sourceforge/schemaspy/util/RailsNamingTest.java:52: cannot find symbol
symbol  : variable Inflection
location: class net.sourceforge.schemaspy.util.RailsNamingTest
        String primaryTableName = Inflection.pluralize(singular);
                                  ^
./src/test/java/net/sourceforge/schemaspy/util/VersionTest.java:29: cannot find symbol
symbol  : class Version
location: class net.sourceforge.schemaspy.util.VersionTest
    private final Version twoNineOne = new Version("2.9.1");
                                           ^
./src/test/java/net/sourceforge/schemaspy/util/VersionTest.java:30: cannot find symbol
symbol  : class Version
location: class net.sourceforge.schemaspy.util.VersionTest
    private final Version twoTen = new Version("2.10");
                                       ^
./src/test/java/net/sourceforge/schemaspy/util/VersionTest.java:31: cannot find symbol
symbol  : class Version
location: class net.sourceforge.schemaspy.util.VersionTest
    private final Version twoTenOne = new Version("2.10.1");
                                          ^
./src/test/java/net/sourceforge/schemaspy/util/VersionTest.java:65: cannot find symbol
symbol  : class Version
location: class net.sourceforge.schemaspy.util.VersionTest
        Version expected = new Version(digits);
        ^
./src/test/java/net/sourceforge/schemaspy/util/VersionTest.java:65: cannot find symbol
symbol  : class Version
location: class net.sourceforge.schemaspy.util.VersionTest
        Version expected = new Version(digits);
                               ^
./src/test/java/net/sourceforge/schemaspy/util/VersionTest.java:67: cannot find symbol
symbol  : class Version
location: class net.sourceforge.schemaspy.util.VersionTest
        assertEquals(expected, new Version(actual));
```

This was after downloading jars for junit and hamcrest-core and putting them in my CLASSPATH.  What version of javac are you using?  Do you have anything else special in your CLASSPATH?

**Comment by robkooper** [comment]
I think you are using wrong version of java. J2SE 8 = 52

**Comment by gsrohde** [comment]
Yes, upgrading allowed me to run the script (though I still couldn't compile from source--not that that matters since the jar file now works).  

Unfortunately, I can no longer seem to run the uncustomized version of schemaSpy, which I found useful as a developer, since it gives more information (a table of a column names, for example, and the tables in which they occur).  The error I get is

```
Using database properties:
  [/Users/srohde/Applications/SchemaSpy/schemaSpy_5.0.0.jar]/net/sourceforge/schemaspy/dbTypes/pgsql.properties
Gathering schema details..........................................................(3sec)
Writing/graphing summary..
Required property 'background' was not found for the definition of '.content' in schemaSpy.css
```

**Comment by gsrohde** [comment]
@phenolphtalein

Is the code at  https://github.com/PecanProject/SchemaSpy-ng up to date?  The version of the jar file at dropbox works, but the release version of the jar file at PecanProject/SchemaSpy-ng does not.  It would be best to have a "permanent" location for a working version of the jar file.

I'm closing this without pulling it: I committed a modified version of your Rake task (in commit 2f3894e7) which doesn't use an external shell script file and gets most of the Schema Spy command line parameters from the Rails environment.

**Pull request closed without merging**
