### PR TITLE
update schema documentation

### PR DESCRIPTION
**Pull request by phenolphtalein**
Updated schema documentation (from #2).

### CODE REVIEW

**Comment by gsrohde** [comment]
I didn't see the traits table in the diagrams and there's not diagram at all on the traits page..  Did I miss something?

**Comment by dlebauer** [comment]
I think her schema is out of date. Updating schema documentation should be
triggered by `rake db migrate` ...

**Comment by gsrohde** [comment]
Are you saying the schema documentation is dynamically generated and will automatically change as the database changes?

**Comment by dlebauer** [comment]
> documentation is dynamically generated and will automatically change as the database changes?

This is what I am asking @phenolphtalein to implement. She has the script, it is just a matter of getting it triggered by `rake` when the schema changes

**Comment by gsrohde** [comment]
So I can pull this in the meantime?

**Comment by dlebauer** [comment]
Don't pull it yet. These files can be removed from the repository.

We just need a trigger (automate) the steps outlined in the [README](https://github.com/PecanProject/bety/blob/master/local/make_documentation_files/README.md) when `rake db migrate` is run.

**Comment by dlebauer** [comment]
@phenolphtalein why close? are you going to submit another pull request (e.g. with less files)? Otherwise, this shouldn't be closed until merged.

**Comment by phenolphtalein** [comment]
Yes, I'm about to submit a different pull request.

**Pull request closed without merging**
