### PR TITLE
Merge remote-tracking branch 'PecanProject/master'

### PR DESCRIPTION
**Pull request by robkooper**

### CODE REVIEW

**Comment by robkooper** [comment]
See https://github.com/PecanProject/pecan/issues/629 and https://github.com/PecanProject/pecan/pull/806

**Comment by gsrohde** [comment]
@robkooper I don't quite get what this is doing.  Why does File changed show nothing?

**Comment by robkooper** [comment]
Ok this time it should be good to go.

**Comment by dlebauer** [comment]
Echoing Mike's comment on the UI the term 'clusters' is ambiguous. sitegroups isn't great but it is more clear.

The field 'everybody' also seems like an awkward term ... wouldn't 'public' be more straightforward? And is there a need to hide site groupings? (Is this just to keep the ad hoc groupings hidden?)

**Comment by robkooper** [comment]
Can't use public since it is a reserved word in ruby. I didn't like network since that has a different conation for me. It needs to be something that fits in ruby land, which is why i picked cluster, so we can have  table called clusters_sites, so something with sitegroups has sites duplicated in the title.

**Comment by gsrohde** [comment]
How about 'openaccess' (or even 'public_access') instead of 'everybody'.  Sure it's longer, but at least it's clear at a glance what it means.  Likewise, using 'sitegroups' in place of 'clusters' results in the redundant 'sites_sitegroups', but so what?  A little redundancy for the sake of clarity doesn't seem a bad trade.

**Comment by mdietze** [comment]
I agree with @gsrohde and @dlebauer suggestions, both on preferring openaccess or public_access to everyone and on preferring sitegroups (or maybe sitenetworks) to clusters.  This fix needs to go in the next PEcAn VM, which we're hoping to build early this week, so hopefully we can get this sorted out, do a quick find-replace, and merge it in.

**Comment by robkooper** [comment]
This is now continued at #407

**Comment by robkooper** [comment]
renamed cluster to be sitegroup and everybody to be public_access

**Pull request closed without merging**
