### PR TITLE
removed 'EBI' from name of access_level=2

### PR DESCRIPTION
**Pull request by dlebauer**
in web app

This change reflects the use of BETYdb beyond the original scope of EBI

### CODE REVIEW

**Comment by dlebauer** [comment]
@gsrohde can this be merged and deployed in the next release?

**Comment by dlebauer** [comment]
@gsrohde can this be merged and deployed in the next release?

**Comment by gsrohde** [comment]
@dlebauer Do you want to change the names of access levels on the traits and yields pages?  We currently use "Restricted", "EBI", "External", and "Public" on the listing pages, the New (create) page form, and the editing form.  (The second and third are abbreviations of "Internal EBI & Collaborators" and "External Researcher", respectively.  The display area on the listing page is more limited, perhaps explaining the abbreviated forms.)  Shall I just use "Internal" in place of "EBI" on the listing page and change to using the full names on the New and Edit pages?

**Comment by dlebauer** [comment]
Yes, please do.

**Comment by dlebauer** [comment]
For such non critical features feel free to implement first ask later

**Comment by gsrohde** [comment]
Closing.  Addressed by commit 1f3e428, which puts dries up the code (so one file controls the selection names) and removes obsolete code.

**Pull request closed without merging**
