### PR TITLE
Sql comments rake task

### PR DESCRIPTION
**Pull request by gsrohde**
This implements the feature in issue #542 using YAML files and Rake tasks.

### CODE REVIEW

**Comment by dlebauer** [comment]
Looks great. Just to confirm, does this feature does the foloowing:

* provides a way of exporting comments in the database
* provides a single canonical place for the comments to be stored (in the .yaml file)
* allows users to import the comments into the local database with a rake task
* provides ruby functions that can be used to query the comments from the database and use this information to populate the API documentation

**Comment by gsrohde** [comment]
It does the first three.  It doesn't provide the Ruby functions to query the comments because they are already there, though it seems from previous comments you have made that they are not going into the API documentation quite where you want them.  I'm considering that a separate issue.

**Comment by dlebauer** [comment]
Approved and Ready to merge, but what is with failing tests?

**Comment by gsrohde** [comment]
The failing tests have something to do with the Travis setup.  I'll make an issue for it if I haven't already.

**Pull request merged**
